<?php
/**
 * Copyright (c) 2020 Ratepay GmbH
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace RpayRatePay\Bootstrap;


use RpayRatePay\Services\Config\ConfigService;
use RpayRatePay\Services\Config\ProfileConfigService;
use RpayRatePay\Services\Config\WriterService;
use RpayRatePay\Services\Logger\RequestLogger;
use RpayRatePay\Services\Request\ProfileRequestService;

class ProfileConfig extends AbstractBootstrap
{

    /**
     * @var ProfileConfigService
     */
    private $profileConfigService;
    /**
     * @var WriterService
     */
    private $profileConfigWriter;

    public function setContainer($container)
    {
        parent::setContainer($container); // TODO: Change the autogenerated stub
        $configService = new ConfigService(
            $this->container,
            $this->container->get('shopware.plugin.cached_config_reader'),
            $this->modelManager,
            $this->installContext->getPlugin()->getName(),
            $this->updateContext ? $this->updateContext->getUpdateVersion() : $this->installContext->getPlugin()->getVersion()
        );
        $this->profileConfigWriter = new WriterService( // TODO uhhh - that's not soo beautiful
            $this->modelManager,
            new ProfileRequestService(
                $db = $this->container->get('db'),
                $configService,
                new RequestLogger(
                    $configService,
                    $this->modelManager,
                    $this->logger
                )
            ),
            $this->logger
        );
        $this->profileConfigService = new ProfileConfigService($this->modelManager, $configService, $this->profileConfigWriter, $this->logger);
    }

    public function activate()
    {
        $this->profileConfigService->refreshProfileConfig();
    }

    public function deactivate()
    {
        $this->profileConfigWriter->deletePaymentConfigs();
    }

    public function install()
    {
        $this->update();
    }

    public function update()
    {
        $db = $this->container->get('db');
        $stmt = $db->query("SHOW TABLES LIKE 'rpay_ratepay_config'");
        if (count($stmt->fetchAll())) {
            $db->exec("INSERT INTO ratepay_profile_config (profile_id, security_code, sandbox, backend, shop_id) SELECT profileId, security_code, sandbox, backend, shopId FROM rpay_ratepay_config");

            // we drop these tables in this script cause the Boostrap `OrderAttributes` will use the old data
            $db->exec('DROP TABLE IF EXISTS rpay_ratepay_config');
            $db->exec("DROP TABLE IF EXISTS rpay_ratepay_config_installment");
            $db->exec("DROP TABLE IF EXISTS rpay_ratepay_config_payment");
        }

        if($this->updateContext) {
            $this->profileConfigService->refreshProfileConfig();
        }
    }

    public function uninstall($keepUserData = false)
    {
        // do nothing
    }
}
